import Navbar from '@/components/Navbar/page'
import './globals.css'
import { Agbalumo } from 'next/font/google'
const mont = Agbalumo({ 
weight:'400',
preload:false })

export const metadata = {
  title: 'Vikas Wiki',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mont.className} bg-[#bb9090] text-white`}>
        <div className='flex flex-col h-screen m-10'>
          <Navbar/>
          <div className='pt-10 border-t border-white col-white'>
            {children}
          </div>
        </div>
        </body>
    </html>
  )
}
